CREATE TABLE app_lock (id INT PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO app_lock VALUES (1);

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','FACTORY','STORE','CUSTOMER') NOT NULL DEFAULT 'CUSTOMER',
  phone VARCHAR(30) NOT NULL DEFAULT '',
  nic VARCHAR(30) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
CREATE TABLE sessions (
  id CHAR(36) PRIMARY KEY,
  user_id INT NOT NULL,
  last_seen DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX ix_sessions_user (user_id)
) ENGINE=InnoDB;
CREATE TABLE stores (
  id INT PRIMARY KEY AUTO_INCREMENT,
  city VARCHAR(60) NOT NULL UNIQUE,
  location VARCHAR(255) NOT NULL,
  manager_id INT UNIQUE,
  FOREIGN KEY (manager_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE routes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  store_id INT NOT NULL,
  name VARCHAR(80) NOT NULL,
  coverage_area VARCHAR(120) NOT NULL UNIQUE,
  max_minutes INT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (store_id) REFERENCES stores(id),
  CHECK (max_minutes BETWEEN 1 AND 480)
) ENGINE=InnoDB;
